variables:
  TF_VAR_env_prefix: "dev"
  TF_VAR_runner_registration_token: $RUNNER_TOKEN
  TF_DIR: "terraform/aws" 

stages:
  - init
  - test
  - build
  - deploy
  - destroy

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

before_script:
 - cd $TF_DIR

init:
  stage: init
  script:
    - terraform init --upgrade
  artifacts:
    paths:
      - $TF_DIR/.terraform/
      - $TF_DIR/.terraform.lock.hcl

validate:
  stage: test
  script:
    - terraform validate
  allow_failure: true

trivy:
  stage: test
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy config --format json . > trivy.json
    - trivy config --exit-code 1 --severity HIGH,CRITICAL .
  allow_failure: true
  artifacts:
    when: always
    paths:
      - $TF_DIR/trivy.json

build:
  stage: build
  script:
    - terraform plan -out "planfile"
  artifacts:
    paths:
      - $TF_DIR/planfile

deploy:
  stage: deploy
  script:
    - terraform apply --input=false "planfile"
  when: manual

plan-destroy:
  stage: destroy
  script:
    - terraform plan -destroy 
  when: manual

destroy:
  stage: destroy
  script:
    - terraform --input=false destroy
  when: manual