variables:
  TF_VAR_env_prefix: "dev"
  TF_VAR_runner_registration_token: $RUNNER_TOKEN
  TF_DIR: "terraform/aws" 

stages:
  - init
  - build
  - deploy

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

before_script:
 - cd $TF_DIR
init:
  stage: init
  script:
    - terraform init
  artifacts:
    paths:
      - $TF_DIR/.terraform/
      - $TF_DIR/.terraform.lock.hcl

build:
  stage: build
  script:
    - terraform plan -out "planfile"
  artifacts:
    paths:
      - $TF_DIR/planfile

deploy:
  stage: deploy
  script:
    - terraform apply --input=false "planfile"
  when: manual